# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ccbea60d5390971a36986e675c806ef45f52c20609098c7de51730f28bff59c356f58276be3f812450401800c178f06b1132066e6cc19e1669cb9dcd849bba7

test:
  secret_key_base: a2924837cdfddb1140cbf790949e6eff189c460bdddeb28d5c51c439aef9d12289f5ac4a14da943ce845f421371841d52a1e3a4c5e393b6273ebe18bc6b131b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
